language: java
sudo: false
jdk:
  - openjdk17
branches:
  only:
    - develop
    - feature/travis-test
cache:
  directories:
    - $HOME/.m2

stages:
  - name: build
  - name: test

jobs:
  include:
    - stage: test
      name: "Run Unit and Integration Tests"
      script:
        - cd livingatlas
        - mvn verify
